#create an artist
POST http://localhost:8080/api/artist
//@no-cookie-jar
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23
X-Csrf-Token: uF8Rtj43_P6eBCcfoApcjNYHOqJ4_tbRV_sWMW4jKTsFW8x8iD0p1V0Ez8uzMR4mlydo6bVhF5sdnLD8NsovUl4QTQg9Y_9M

    {
    "artistName" : "DongDing",
    "artistFollowers" : 1
    }

###Response:
//Response code: 401; Time: 3ms (3 ms); Content length: 0 bytes (0 B)

###
#get an artist
GET http://localhost:8080/api/artist/1
//@no-cookie-jar
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

//Response:

//{
//  "id": 1,
//  "name": "The Beatles",
//  "artistFollowers": 1231.0
//}
#Response Code: 200; Time: 8ms (8 ms); Content length: 70 bytes (70 B)

###
#delete an artist
# @no-cookie-jar
DELETE http://localhost:8080/api/artist/1/delete
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

//Response:
//Response code: 401; Time: 3ms (3 ms); Content length: 0 bytes (0 B)

###

#Get All Artists
# @no-cookie-jar
GET http://localhost:8080/api/artists
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "name": "The Beatles",
#    "artistFollowers": 1231.0
#  },
#  {
#    "id": 2,
#    "name": "The Rolling Stones",
#    "artistFollowers": 1231.0
#  },
#  {
#    "id": 3,
#    "name": "The Doors",
#    "artistFollowers": 1231.0
#  },
#....

###
#get a album
# @no-cookie-jar
GET http://localhost:8080/api/album/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

//Response:
#{
#  "id": 1,
#  "albumName": "Abbey Road",
#  "artistName": null,
#  "genre": "Rock",
#  "officialTrackCount": 12,
#  "albumStatus": "SINGLE",
#  "releaseDate": "1969-09-26"
#}
#Response file saved.
#> 2023-03-26T215223.200.json
#
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)

###
#delete a album
# @no-cookie-jar
DELETE http://localhost:8080/api/album/1/delete
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

//Response:
#Response code: 401; Time: 3ms (3 ms); Content length: 0 bytes (0 B)

###
#Get All Albums
# @no-cookie-jar
GET http://localhost:8080/api/albums
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "albumName": "Abbey Road",
#    "artistName": "The Beatles",
#    "genre": "Rock",
#    "officialTrackCount": 12,
#    "albumStatus": "SINGLE",
#    "releaseDate": "1969-09-26"
#  },
#  {
#    "id": 2,
#    "albumName": "Let It Bleed",
#    "artistName": "The Rolling Stones",
#    "genre": "Rock",
#    "officialTrackCount": 12,
#    "albumStatus": "SINGLE",
#    "releaseDate": "1969-08-05"
#  },
#.....
#Response code: 200; Time: 24ms (24 ms); Content length: 1414 bytes (1.41 kB)


###
# get a artists albums
# @no-cookie-jar
GET http://localhost:8080/api/artist/1/albums
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "albumName": "Abbey Road",
#    "artistName": "The Beatles",
#    "genre": "Rock",
#    "officialTrackCount": 12,
#    "albumStatus": "SINGLE",
#    "releaseDate": "1969-09-26"
#  }
#]
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)



###
#get a albums songs
# @no-cookie-jar
GET http://localhost:8080/api/album/1/songs
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "songTitle": "Tantrum",
#    "trackNumber": 2,
#    "durationMs": 134112.0,
#    "explicit": true,
#    "url": "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO"
#  },
#  {
#    "id": 2,
#    "songTitle": "I Don't Wanna Dance",
#    "trackNumber": 2,
#    "durationMs": 134112.0,
#    "explicit": true,
#    "url": "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO"
#  },
//.....
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)

###
#get a song
# @no-cookie-jar
GET http://localhost:8080/api/song/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#{
#  "id": 1,
#  "songTitle": "Tantrum",
#  "trackNumber": 2,
#  "durationMs": 134112.0,
#  "explicit": true,
#  "url": "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO"
#}
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)

###
#get all songs
# @no-cookie-jar
GET http://localhost:8080/api/songs
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "songTitle": "Tantrum",
#    "trackNumber": 2,
#    "durationMs": 134112.0,
#    "explicit": true,
#    "url": "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO"
#  },
#  {
#    "id": 2,
#    "songTitle": "I Don't Wanna Dance",
#    "trackNumber": 2,
#    "durationMs": 134112.0,
#    "explicit": true,
#    "url": "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO"
#  },
#....
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)

###
#get all artists for an album
# @no-cookie-jar
GET http://localhost:8080/api/album/1/artists
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

#resposnse
#[
#  {
#    "id": 1,
#    "name": "The Beatles",
#    "artistFollowers": 1231.0
#  }
#]
#Response code: 200; Time: 8ms (8 ms); Content length: 140 bytes (140 B)



###
#create a album for an artist
# @no-cookie-jar
POST http://localhost:8080/api/artist/1/album/create
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23
X-CSRF-TOKEN: 8d8b076f-2ac7-4929-9427-0acf24d1e928

{
  "albumName": "The Dark Side of the Moon",
  "trackCount": 1,
  "albumStatus": "SINGLE",
  "genre": "Progressive Rock",
  "releaseDate": "1973-03-01"
}
### response
#Response code: 401; Time: 4ms (4 ms); Content length: 0 bytes (0 B)


###
#create a song for an album
# @no-cookie-jar
POST http://localhost:8080/api/album/1/song/create
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

{
  "url": "https://open.spotify.com/track/2YFtpiy2WoAQVQbM1SIwES",
  "trackCount": 1,
  "albumStatus": "SINGLE",
  "genre": "Progressive Rock",
  "releaseDate": "1973-03-01"
}
### response
#Response code: 401; Time: 4ms (4 ms); Content length: 0 bytes (0 B)
###
#delete a song
# @no-cookie-jar
DELETE http://localhost:8080/api/song/1/delete
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=B282F54D6CEB53A022232BB1799DE503

### response
#Response code: 401; Time: 4ms (4 ms); Content length: 0 bytes (0 B)
