
POST http://localhost:8080/api/artist/create
//@no-cookie-jar
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

    {
    "artistName" : "DongDing",
    "artistFollowers" : 1
    }

###
GET http://localhost:8080/api/artist/1
//@no-cookie-jar
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

###
# @no-cookie-jar
DELETE http://localhost:8080/api/artist/1/delete

###
# @no-cookie-jar
GET http://localhost:8080/api/artists

###
# @no-cookie-jar
GET http://localhost:8080/api/album/1

###
# @no-cookie-jar
DELETE http://localhost:8080/api/album/1/delete

###
# @no-cookie-jar
GET http://localhost:8080/api/albums
###
# @no-cookie-jar
GET http://localhost:8080/api/artist/1/albums
###
# @no-cookie-jar
GET http://localhost:8080/api/album/1/songs

###
# @no-cookie-jar
GET http://localhost:8080/api/song/1
###
# @no-cookie-jar
GET http://localhost:8080/api/songs
###
# @no-cookie-jar
GET http://localhost:8080/api/album/1/artists
###
# @no-cookie-jar
POST http://localhost:8080/api/artist/1/album/create
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

{
  "albumName": "The Dark Side of the Moon",
  "trackCount": 1,
  "albumStatus": "SINGLE",
  "genre": "Progressive Rock",
  "releaseDate": "1973-03-01"
}
###
# @no-cookie-jar
POST http://localhost:8080/api/album/1/song/create
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23

{
  "url": "https://open.spotify.com/track/2YFtpiy2WoAQVQbM1SIwES",
  "trackCount": 1,
  "albumStatus": "SINGLE",
  "genre": "Progressive Rock",
  "releaseDate": "1973-03-01"
}
###
# @no-cookie-jar
DELETE http://localhost:8080/api/song/1/delete
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=75400D8A8763ED4F6B3220A14694DA23
